meta:
  repo-name: my-repo
  repo-url: https://mydehq.github.io/my-repo
  project-url: https://github.com/mydehq/my-repo

packages:
  aur:
    # Official projects
    - name: myctl
    - name: mytm
    - name: nautilus-dummy
    - name: nsticky-bin
    - name: autotitle

    # 3rd party
    - name: kireisakura-kit
    - name: dms-shell-bin
    - name: mpv-mpris2-bin
    - name: vicinae-bin
    - name: app2unit
    - name: catppuccin-cursors-macchiato
    - name: vorta-root
    - name: ttf-sil-abyssinica
    - name: git-credential-keepassxc-bin
    - name: catnap
    - name: python-textual-fastdatatable-latest
    - name: sqlit
